export const theme = {
  colors: {
    black: 'var(--color-black)',
    darkGray: 'var(--color-gray-dark)',
    gray: 'var(--color-gray)',
    lightGray: 'var(--color-gray-light)',
    white: 'var(--color-white)',
    red: 'var(--color-red',
    lighterGreen: 'var(--color-green-lighter)',
    lightGreen: 'var(--color-green-light)',
    green: 'var(--color-green)',
    lightPurple: 'var(--color-purple-light)',
    purple: 'var(--color-green-purple)',

    primary: 'var(--color-primary)',
    secondary: 'var(--color-secondary)',
  },
  breakpoints: {
    mobile_small: '375px',
    mobile_medium: '515px',
    mobile_large: '650px',
    tablet_small: '768px',
    tablet_medium: '900px',
    tablet_large: '1024px',
    desktop_small: '1280px',
    desktop_large: '1440px',
  },
  layout: {
    space100: 'var(--gutter-100)',
    space200: 'var(--gutter-200)',
    space300: 'var(--gutter-300)',
    space400: 'var(--gutter-400)',
    pageWrapperMaxWidth: 'var(--page-wrapper-max-width)',
  },
  typography: {
    familyPrimary: 'var(--font-family-primary)',
    fs75: 'var(--font-size-75)',
    fs87: 'var(--font-size-87)',
    fs100: 'var(--font-size-100)',
    fs112: 'var(--font-size-112)',
    fs125: 'var(--font-size-125)',
    fs150: 'var(--font-size-150)',
    weightNormal: 'var(--font-weight-normal)',
    weightHeavy: 'var(--font-weight-heavy)',
  },
}
